#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Terasploit Framework - A modular penetration testing framework.


# Python lib
import sys

if sys.argv[1:]:
    print(sys.argv[1:])
    raise SystemExit(0)

# Starts command line interface if no argv is specified.

# Framework
from framework.console.cli import Interpreter

# Starts the console CLI
console_cli = Interpreter()
console_cli.main()
